/**
 * @fileoverview Simplified theme provider
 * @description Theme context provider with class-based theme switching
 * @package @voilajsx/uikit
 * @file /src/themes/theme-provider.jsx
 */

import { createContext, useContext, useEffect, useState } from 'react';

// Available themes registry
// This info could be auto-generated by the theme-generator script
const AVAILABLE_THEMES = [
  { id: 'default', name: 'Default' },
  { id: 'ocean', name: 'Ocean' },
  { id: 'forest', name: 'Forest' },
  { id: 'sunset', name: 'Sunset' }
];

// Theme context
const ThemeContext = createContext({
  theme: 'default',
  variant: 'light',
  setTheme: () => {},
  setVariant: () => {},
  toggleVariant: () => {},
  availableThemes: AVAILABLE_THEMES
});

/**
 * Theme provider component
 * @param {Object} props - Component props
 * @param {React.ReactNode} props.children - Child components
 * @param {string} [props.theme='default'] - Initial theme
 * @param {'light'|'dark'} [props.variant='light'] - Initial variant
 * @param {boolean} [props.detectSystem=true] - Detect system preference
 * @returns {JSX.Element} Theme provider component
 */
export function ThemeProvider({
  children,
  theme = 'default',
  variant = 'light',
  detectSystem = true
}) {
  const [themeState, setThemeState] = useState({
    theme: theme,
    variant: variant
  });

  // Initialize theme from localStorage or props
  useEffect(() => {
    if (typeof window === 'undefined') return;
    
    try {
      // Try to load saved preferences
      const saved = localStorage.getItem('uikit-theme');
      if (saved) {
        const { theme, variant } = JSON.parse(saved);
        setThemeState({ theme, variant });
      } else if (detectSystem) {
        // Check system preference
        const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
        if (prefersDark) {
          setThemeState(prev => ({ ...prev, variant: 'dark' }));
        }
      }
    } catch (e) {
      // Ignore errors
    }
  }, [detectSystem]);
  
  // Apply theme classes when state changes
  useEffect(() => {
    if (typeof window === 'undefined') return;
    
    const { theme, variant } = themeState;
    const root = document.documentElement;
    
    // Remove existing theme classes
    root.classList.remove('dark', 'light');
    AVAILABLE_THEMES.forEach(t => {
      root.classList.remove(`theme-${t.id}`);
    });
    
    // Add new theme classes
    if (theme !== 'default') {
      root.classList.add(`theme-${theme}`);
    }
    root.classList.add(variant);
    
    // Save preferences
    try {
      localStorage.setItem('uikit-theme', JSON.stringify({ theme, variant }));
    } catch (e) {
      // Ignore storage errors
    }
  }, [themeState]);
  
  // Listen for system preference changes
  useEffect(() => {
    if (!detectSystem || typeof window === 'undefined') return;
    
    const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)');
    
    const handleChange = (e) => {
      // Only update if user hasn't explicitly chosen a theme
      try {
        const saved = localStorage.getItem('uikit-theme');
        if (!saved) {
          setThemeState(prev => ({
            ...prev,
            variant: e.matches ? 'dark' : 'light'
          }));
        }
      } catch (e) {
        // Ignore storage errors
      }
    };
    
    mediaQuery.addEventListener('change', handleChange);
    return () => mediaQuery.removeEventListener('change', handleChange);
  }, [detectSystem]);
  
  // Create context value
  const contextValue = {
    theme: themeState.theme,
    variant: themeState.variant,
    availableThemes: AVAILABLE_THEMES,
    
    setTheme: (newTheme) => {
      // Accept both strings and theme objects
      if (typeof newTheme === 'string') {
        if (AVAILABLE_THEMES.some(t => t.id === newTheme)) {
          setThemeState(prev => ({ ...prev, theme: newTheme }));
        }
      } else if (typeof newTheme === 'object' && newTheme.id) {
        // Custom theme object
        setThemeState(prev => ({ ...prev, theme: newTheme.id, customTheme: newTheme }));
      }
    },
    
    setVariant: (newVariant) => {
      if (newVariant === 'light' || newVariant === 'dark') {
        setThemeState(prev => ({ ...prev, variant: newVariant }));
      }
    },
    
    toggleVariant: () => {
      setThemeState(prev => ({
        ...prev,
        variant: prev.variant === 'light' ? 'dark' : 'light'
      }));
    }
  };
  
  return (
    <ThemeContext.Provider value={contextValue}>
      {children}
    </ThemeContext.Provider>
  );
}

/**
 * Hook to access theme context
 * @returns {Object} Theme context value
 */
export function useTheme() {
  const context = useContext(ThemeContext);
  if (!context) {
    throw new Error('useTheme must be used within a ThemeProvider');
  }
  return context;
}